<?xml version="1.0"?>
<robot name="base_link" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:macro name="base_link" params="originZ base_width base_length base_height lower_base_height base_space_height base_space_width"> <!--fb : front, back ; lr: left, right -->
        <!-- The lower part of the base link -->
        <link name="base_link">
            <collision>
                <origin xyz="0 0 ${originZ}" rpy="0 0 0"/>
                <geometry>
                    <box size="${base_width} ${base_length} ${lower_base_height}"/>
                </geometry> 
            </collision>
            <visual>
                <origin xyz="0 0 ${originZ}" rpy="0 0 0"/>
                <geometry>
                    <box size="${base_width} ${base_length} ${lower_base_height}"/>
                </geometry>
            </visual>
            <inertial>
                <origin xyz="0 0 ${originZ}" rpy="0 0 0"/>
                <mass value="4"/>
                <box_inertia m="4" x="${base_width}" y="${base_length}" z="${lower_base_height}"/>
            </inertial>
        </link>
        <gazebo reference="base_link">
            <material>Gazebo/Grey</material>
        </gazebo>

        <!-- The middle part of the base link -->
        <link name="mid_base_link">
            <collision>
                <origin xyz="0 0 ${originZ}" rpy="0 0 0"/>
                <geometry>
                    <box size="${base_width - base_space_width} ${base_length} ${base_space_height}"/>
                </geometry> 
            </collision>
            <visual>
                <origin xyz="0 0 ${originZ}" rpy="0 0 0"/>
                <geometry>
                    <box size="${base_width - base_space_width} ${base_length } ${base_space_height}"/>
                </geometry>
            </visual>
            <inertial>
                <origin xyz="0 0 ${originZ}" rpy="0 0 0"/>
                <mass value="2"/>
                <box_inertia m="2" x="${base_width - base_space_width}" y="${base_length}" z="${base_space_height}"/>
            </inertial>
        </link>
        <gazebo reference="mid_base_link">
            <material>Gazebo/Grey</material>
        </gazebo>

        <!-- The top part of the base link -->
        <link name="top_base_link">
            <collision>
                <origin xyz="0 0 ${originZ}" rpy="0 0 0"/>
                <geometry>
                    <box size="${base_width} ${base_length} ${base_height - base_space_height - lower_base_height}"/>
                </geometry> 
            </collision>
            <visual>
                <origin xyz="0 0 ${originZ}" rpy="0 0 0"/>
                <geometry>
                    <box size="${base_width} ${base_length} ${base_height - base_space_height - lower_base_height}"/>
                </geometry>
            </visual>
            <inertial>
                <origin xyz="0 0 ${originZ}" rpy="0 0 0"/>
                <mass value="4"/>
                <box_inertia m="4" x="${base_width}" y="${base_length}" z="${base_height - base_space_height - lower_base_height}"/>
            </inertial>
        </link>
        <gazebo reference="top_base_link">
            <material>Gazebo/Grey</material>
        </gazebo>


        <!-- The joint between the lower and middle part of the base link -->
        <joint name="lower_mid_joint" type="fixed">
            <origin xyz="${-(base_width/2 - (base_width - base_space_width)/2)} 0 ${lower_base_height/2 + base_space_height/2}" />
            <parent link="base_link"/>
            <child link="mid_base_link"/>
        </joint>

        <!-- The joint between the middle and top part of the base link -->
        <joint name="mid_top_joint" type="fixed">
            <origin xyz="${base_width/2 - (base_width - base_space_width)/2} 0 ${(base_height - base_space_height - lower_base_height)/2 + base_space_height/2}" />
            <parent link="mid_base_link"/>
            <child link="top_base_link"/>
        </joint>
    </xacro:macro>
</robot>
